---
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    uses: xebis/github-actions-and-workflows/.github/workflows/semantic-release.yaml@v0
    with:
      GH_APP_ID: ${{ vars.GH_APP_SEM_REL_ID }}
    secrets:
      GH_APP_PEM_FILE: ${{ secrets.GH_APP_SEM_REL_PEM_FILE }}
